name: eShopOnWeb Build and Test
# on: [workflow_dispatch]
on: [push, workflow_dispatch]

#Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE-GROUP: Tahira1s-test-rg
  LOCATION: westeurope
  TEMPLATE-FILE: .azure/bicep/webapp.bicep
  SUBSCRIPTION-ID: ${{ secrets.subscriptionId }}
  WEBAPP-NAME: az400-fdwebapp21-tahira00test

jobs:
  buildandtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true  

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test with dotnet
        run: dotnet test  --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      # upload the bicep template as artifacts for next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}  

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: .net-app
 #Download the bicep templates from previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: bicep-template
          path: bicep-template
        
  # Login in your azure subscription using a service principal (credentials stored as GitHub Secret in repo)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  # create resource group
      - name: Azure CLI Create resource group  
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az group create -n ${{ env.RESOURCE-GROUP }} -l 'West Europe'    
  
  # Deploy Azure WebApp using Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/webapp.bicep
          parameters: 'webAppName=${{ env.WEBAPP_NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false   

  # publish content to Azure Web App
      - name: Publish Website to WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: .net-app
